# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "a650a3de-e61f-4907-93de-87cd227d3dde"

default_platform :android

platform :android do

  before_all do

  end

  after_all do |lane|
    
  end

  error do |lane, exception|
    
  end

  desc "Send Debug Stage app to Crashlytics Beta"
  lane :deploy do
    version_number = sh("git describe --tags --exact-match")
    version_number.delete!("\n")
    sh("find .. -name 'build.gradle' -exec ./update_version.sh {} \\;")
    puts version_number
    puts version_number
    add_git_tag(tag: "v#{version_number}")
    git_commit(path: "**/build.gradle", message: "Increase build number")
    push_to_git_remote
    
    # gradle(task: 'app:assembleProdRelease')
    # supply(
    #   track: 'rollout',
    #   rollout: '0.5',
    #   apk: 'app/build/outputs/apk/prod/release/app-prod-release.apk')
  end

  desc "Upload to Google Play Beta"
  lane :beta do
    gradle(task: 'app:assembleProdRelease')
    supply(
      track: 'beta',
      apk: 'app/build/outputs/apk/prod/release/app-prod-release.apk')
  end

end
