# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "a650a3de-e61f-4907-93de-87cd227d3dde"

default_platform :android

platform :android do

  before_all do

  end

  after_all do |lane|
    slack(message: "Successfully executed lane #{lane}")
  end

  error do |lane, exception|
    slack(message: exception.message, success: false)
  end

  desc "Send Debug Stage app to Crashlytics Beta"
  lane :deploy do
    sh("find .. -name 'build.gradle' -exec ./update_version.sh {} \;")
    gradle(task: 'app:assembleProdRelease')
    supply(
      track: 'rollout', 
      rollout: '0.5', 
      apk: 'app/build/outputs/apk/prod/release/app-prod-release.apk')
  end

  desc "Upload to Google Play Beta"
  lane :beta do
    gradle(task: 'app:assembleProdRelease')
    supply(
      track: 'beta',
      apk: 'app/build/outputs/apk/prod/release/app-prod-release.apk')
  end

end
